project_name: tparallel
before:
  hooks:
    - go mod tidy
builds:
  - main: ./cmd/tparallel
    binary: tparallel
    ldflags:
      - -s -w
      - -X main.Version={{.Version}}
      - -X main.Revision={{.ShortCommit}}
    env:
      - CGO_ENABLED=0
archives:
  - name_template: >-
      {{ .ProjectName }}_
      {{- .Version }}_
      {{- if eq .Os "freebsd" }}FreeBSD
      {{- else }}{{ title .Os }}{{ end }}_
      {{- if eq .Arch "amd64" }}64bit
      {{- else if eq .Arch "386" }}32bit
      {{- else if eq .Arch "arm64" }}ARM64
      {{- else if eq .Arch "riscv64" }}RISCV
      {{- else }}{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}{{ end }}
    format_overrides:
      - goos: windows
        format: zip
release:
  prerelease: auto
brews:
  - tap:
      owner: moricho
      name: homebrew-tparallel
    homepage: https://github.com/moricho/tparallel
    description: tparallel detects inappropriate usage of t.Parallel() method in your Go test codes
    install: |
      bin.install "tparallel"
    test: |
      system "#{bin}/goreleaser -v"
